name: uri
version: 0.11.0
author: Dart Authors <misc@dartlang.org>
description: Utilities for building and parsing URIs
homepage: https://github.com/google/uri.dart
environment:
  sdk: '>=1.12.0'
dependencies:
  matcher: '>=0.12.0 <0.13.0'
  quiver: '>=0.17.0 <0.25.0'
  utf: '>=0.8.10 <=0.10.0'
dev_dependencies:
  test: '>=0.12.0 <=0.13.0'
